### ISSUE TITLE
Поиск по сайту anilibria.tv

### ISSUE THREAD

**Issue by rus364** [Eviloid/kodi.repository#1]
Доброго времени суток.
Работа проделанная вами, это просто потрясающе... Тем не менее, если нужно найти что-то конкретное на anilibria.tv, это превращается в пытку. Добавьте пожалуйста поиск в будущих релизах.
И самое главное, просто хотелось морально поддержать. Качество плагинов на высочайшем уровне! Прошу, не забрасывайте свою грандиозную работу.

**Comment by Eviloid** [comment]
Весьма польщен. Спасибо Вам за добрые слова!
Поиск сделал. В настройках добавил пункт "Показывать описание в поиске" - если включить - поиск будет помедленнее, но более информативный.

**Comment by rus364** [comment]
Большое спасибо!
