### ISSUE TITLE
В некоторых аниме отсутствуют раздачи (Anilibria)

### ISSUE THREAD

**Issue by rus364** [Eviloid/kodi.repository#2]
Добрый вечер, это снова я)
В некоторых аниме, когда открываешь список серий, отсутствует возможность выбрать торрент-раздачу. Онлайн просмотр при этом есть, но иногда он работает странно (плеер сам пропускает несколько секунд видео и воспроизводит дальше). Вот список онгоингов с первых страниц по которым заметил проблему с отсутствующими раздачами:

- Грабитель
- Шерлок из Кабуке-тё
- Волшебник-воин Орфен
- Волейбол!! К вершине
- Бесконечный Дендрограм
- Кошачий рай (TV)

Может там что-то отличается в ссылках и не парсится...

А ещё, вам стоит добавить в описание плагинов свои реквизиты. За такую работу, я бы лично сделал хотя бы небольшой взнос) Ну и в какие-нибудь известные репы прописать плагины, типа того же xbmc search db.

**Comment by Eviloid** [comment]
Добрый!

Благодарю за отзыв. Я очень рад, что кто-то всё таки нашёл да ещё и пользуется моими поделками ;)

По поводу описанных проблем:

- Торренты не видны

Как я понимаю их убрали с сайта для определенных релизов. Но в настройках есть пункт **Альтернативный способ получения torrent-файлов** включите его и торренты должны появится ;)

- Онлайн просмотр работает "странно"

Там hls-поток и в обычном режиме Kodi съедает 3 первых секунды чтобы определить "формат" (ну тут я не очень разбираюсь, это как я сам понял). Самого этот факт бесил - поэтому в настройках есть пункт **Использовать InputStream Adaptive** - надо включить, но перед этим установить из стандартного репа kodi аддон **InputStream Adaptive**, он находится в разделе _VideoPlayer InputStream_

Надеюсь это поможет.

По поводу _взносов_, Заманчиво конечно, но всё таки я "паразитирую" на чужом контенте - поэтому **нет**. Думаю, будет честнее поблагодарить ребят, кто занимается озвучкой. Поддержите их и будем дальше наслаждаться классными аниме! ;)

В "известные репы" - не, не хочу, лишняя известность ни к чему. Много пользователей - много пожеланий, проблем каких-то. Неее, саппорт - это не моё ;)

**Comment by rus364** [comment]
О, и правда, вы всё учли заранее. Не пришло в голову залезть в настройки)
А современных дабберов да, согласен, нужно поддерживать. Вспоминая старые озвучки, хочется плакать...
В любом случае, спасибо вам ещё раз за ваш труд и ответы на вопросы. Будучи админом, хорошо понимаю вашу ненависть к саппорту)
