### ISSUE TITLE
Просто вопрос из интереса)

### ISSUE THREAD

**Issue by rus364** [Eviloid/kodi.repository#3]
Добрый вечер!
Не нашёл как оставить личное сообщение. Заметил что в последнем обновлении анилибрии вы исправили досадную проблему с воспроизведением торрентов, довольно своеобразным образом.
Дело в том что я сам очень хочу изучить питон и пытался разобраться в вашем коде. Ну и не хотелось вас засыпать такими вот проблемами, думал может сам смогу починить... Пока не всё понял, но очень интересно почему так странно парсятся раздачи у анилибрии? Раньше серии в раздачах выбирались просто рендомно. Есть ли какой-то алгоритм в этом?

**Comment by rus364** [comment]
Из последних коммитов что-то не понял... Или может проблема только у меня. Хотя странно тогда, что теперь в раздачах повторно предлагается выбор серии, после обновления.
Кстати, не в тему конечно, но почему вы убрали поддержку прокси? Просто я только сейчас заметил)

**Comment by rus364** [comment]
С гитхабом бы разобраться сначала, да, знаю) Может я просто не нашёл нужный коммит...

**Comment by Eviloid** [comment]
Добрый! ;)

А вы каким движком пользуетесь для просмотра торрентов? Часом не elementum?
Мне просто не понятно вот это _"Раньше серии в раздачах выбирались просто рандомно"_.
Это что-то типа выбираешь 1 серию, а воспроизводится 3-я например, так?
А _"повторно предлагается выбор серии, после обновления"_ это как? Я просто пользуюсь t2h или TAM+t2h описанного поведения ни разу не замечал.

Прокси я добавил когда их блочить стали. Но затем я решил вопрос на роутере, а теперь вроде блокировку сняли. Да и реализация прокси мне не нравилась - решил выпилить.
В версии 0.6 выпилил, в [0.5.9](https://github.com/Eviloid/kodi.repository/blob/6109964b119bd25dbeffdd17738d5601b616a4e7/plugin.video.evld.anilibria.tv/plugin.video.evld.anilibria.tv-0.5.9.zip) работа через прокси есть.

Можете меня в Skype по нику найти, можем там пообщаться если есть желание.
